---
# Значения по умолчанию для роли ssh_audit
ssh_audit_sshd_config_path: "/etc/ssh/sshd_config"
ssh_audit_expected:
  PermitRootLogin: "no"
  PasswordAuthentication: "no"
  MaxAuthTries: "6"
  ChallengeResponseAuthentication: "no"
  X11Forwarding: "no"
ssh_audit_log_path: "/var/log/ansible-ssh-audit.log"
