name: ansible-ssh-audit-ci
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint
      - name: Run ansible-lint
        run: ansible-lint
      - name: Run yamllint
        run: yamllint .
  build-test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t ssh-audit-eda:ci -f docker/Dockerfile .
      - name: Run container
        run: |
          mkdir -p logs
          docker run --rm \
            -v ${{ github.workspace }}/example:/example:ro \
            -v ${{ github.workspace }}/logs:/var/log \
            ssh-audit-eda:ci
      - name: Check JSON log with jq
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          jq -e . ./logs/ansible-ssh-audit.log > /dev/null
